#!/usr/bin/env ruby

require 'rubygems'
require 'rake'

spec = Gem::Specification.find_by_name 'lambda_punch'
load "#{spec.gem_dir}/lib/lambda_punch/tasks/install.rake"

command = ARGV[0] || 'install'

Rake::Task["lambda_punch:#{command}"].invoke
